### ISSUE TITLE
Add Accept option to clipper-upload component

### ISSUE THREAD

**Issue by dritir** [timtnleeProject/vuejs-clipper#1]
Hi, 

file: clipper-upload.vue

Adding a prop `accept` like so:
`
<input type="file" class="upload" @input="upload($event)" @click="clear($event)" :accept="accept" style="display:none">
`

`
  props: {
    value: {
      type: String,
      default: ''
    },
    accept: {
      type: String,
      default: '*'
    },
    check: {
      type: Boolean,
      default: true
    }
  },
`
Would allow mobile devices to change input dialog. I use "image/jpeg,image/png" which brings last used images, gallery and camera access.

**Comment by timtnleeProject** [comment]
Hi, @dritir 
can you describe more about what you want to achieve?

I don't understant what are 
`"allow mobile devices to change input dialog"` and 
`"brings last used images, gallery and camera access"`

Thanks!

**Comment by dritir** [comment]
Sure, open this sandbox on your android.
https://p9j2zw87qj.codesandbox.io/

First input selects camera and photo related stuff.

Second input asks for many apps, because it accepts .pdf for example.
