### ISSUE TITLE
Fixed Clipper Programmatic zoom

### ISSUE THREAD

**Issue by rferreira98** [timtnleeProject/vuejs-clipper#103]
Clipper basic allows the use of a clipper range (e.g) to rotate and scale programmatically. Clipper fixed does not and it is as important as it is in Clipper Basic functionalities.

Would be very appreciative of the ability to perform a zoom on the Clipper Fixed component.

**Comment by francoguilherme** [comment]
I would like this very much. I want to use a slider or buttons to perform zoom on clipper-fixed, in case the user can't use mouse wheel on desktop. Please add this option!

**Comment by murillobazz** [comment]
Glad to see that the functionality I've been looking for is already in here! Looking forward to this implementation, been struggling with the same needs already pointed out up here... Fingers crossed for seeing this coming to life ASAP! :)

**Comment by francoguilherme** [comment]
There's actually an easy work around for this (issue #79).

**Comment by rferreira98** [comment]
> There's actually an easy work around for this (issue #79).

I cannot make it work in my project.

**Comment by francoguilherme** [comment]
Yeah even if it's working for me the input value is starting at 0, even though the scale is set to initialize with 1.

**Comment by timtnleeProject** [comment]
A possible solution to control scaling by yourself:
https://codesandbox.io/s/clipper-fixed-scale-control-7yrqk
