### ISSUE TITLE
Animated GIFs not working

### ISSUE THREAD

**Issue by rferreira98** [timtnleeProject/vuejs-clipper#108]
**Describe the bug**
Uploading an animated GIF and clipping it does not result in an animate clipped image.

**To Reproduce**
1. Upload animated GIF
2. Clip
3. Result is not animated

**Expected behavior**
Expected to see a clip of the animated GIF.

**Desktop & Smartphone:**
 - Any platform.

**Comment by timtnleeProject** [comment]
@rferreira98 sorry but .gif need special tools to edit/crop.
 The component will not support gif image.
