### ISSUE TITLE
img-pos not update on load

### ISSUE THREAD

**Issue by Afondevi** [timtnleeProject/vuejs-clipper#11]
img-pos not update on load,

see picture on load :
<img width="759" alt="Capture d’écran 2019-04-18 à 11 28 43" src="https://user-images.githubusercontent.com/11740298/56351697-fd74f000-61cd-11e9-980e-d8bcb5a4dfe5.png">

Maybe because I change the `.zoom-area` element in javascript like that ? 
```javascript
const cropper = document.querySelector(".cropper");
const roomArea = document.querySelector(".cropper .zoom-area");
if(cropper.offsetHeight > cropper.offsetWidth){
    roomArea.style.height = `${cropper.offsetWidth}px`;
    roomArea.style.width = `${cropper.offsetWidth}px`;
}else if(cropper.offsetHeight < cropper.offsetWidth){
    roomArea.style.height = `${cropper.offsetHeight}px`;
    roomArea.style.width = `${cropper.offsetHeight}px`;
}else{
    roomArea.style.height = "100%";
    roomArea.style.width = "100%";
}
roomArea.style.top = `calc(50% - ${(roomArea.offsetHeight/2)}px)`;
roomArea.style.left = `calc(50% - ${(roomArea.offsetWidth/2)}px)`;
```

if is not good, can you explain me how change zoom area size to get all size of image by default. thanks

**Comment by timtnleeProject** [comment]
Hi @Afondevi ,
zoom area's reactive positions and sizing(width, height) are variables that subscribed to *rxjs* observables.
Now there is a subject called `setTL$` that can set zooming area's position (top, left).
usage:
```javascript
this.$refs.clipper.setTL$.next({
  top: 0, // 0%
  left: 0
})
```

However, there is no `setWH$` subject to let you set the width and height of the zooming area.

## Todo

I will add this feature on the next version and update document(and examples maybe), so it might take some days.

## Expect
to set the zooming area after the image loaded

```javscript
this.$refs.clipper.setTL$.next({
  top: 0, // 0%
  left: 0
})
this.$refs.clipper.setWH$.next({
  width: 100, // 100%
  height: 100
})
```

thanks!

**Comment by Afondevi** [comment]
Hi @timtnleeProject  :)

Good to see that !
I think it a must have features to add in your project :)

Thanks so much to work on it.

Alex

**Comment by timtnleeProject** [comment]
One of the reasons not using `px` is that using `%` can keep the whole component responsive so that you can set the width of the clipping component to `%`.

**Comment by Afondevi** [comment]
Yes of course 👌🏻
