### ISSUE TITLE
sass warning when build packages

### ISSUE THREAD

**Issue by namlulu** [timtnleeProject/vuejs-clipper#114]
**Describe the bug**

During the build of the nuxt project, a warning or appears about the divide operator. Every time you perform a build, changing the code yourself is too much. What should I do to solve this problem?

**To Reproduce**
1. build vuejs-clipper using docker

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/60912642/131595563-b3ae6112-994f-41b7-acd6-0db0e2bd26f4.png)

![image](https://user-images.githubusercontent.com/60912642/131595595-133f26e4-a857-4a33-bc3e-5ddb80f4332f.png)

![image](https://user-images.githubusercontent.com/60912642/131595618-a37c7150-cdae-4c0f-80a3-7a25da150744.png)

**Comment by namlulu** [comment]
"resolutions": {
	"sass": "1.32.12"
}

**Comment by timtnleeProject** [comment]
Hi @namlulu ,
do you mind making a Pr for this?

If you're using the dist script also solve the problem:
```javascript
import VuejsClipper from "vuejs-clipper/dist/vuejs-clipper.umd";
import "vuejs-clipper/dist/vuejs-clipper.css";
```

**Comment by MitsuhaKitsune** [comment]
The correct fix isn't downgrade sass, just use math.div instead /

I send a PR to fix this
