### ISSUE TITLE
bugged npm 3.2.0 version (Migrate to v4)

### ISSUE THREAD

**Issue by mrquokka** [timtnleeProject/vuejs-clipper#116]
**Describe the bug**
in 3.2.0 have syntax error translate(math...

**To Reproduce**
1. Install 3.2.0 version

**Expected behavior**
Work

**Comment by timtnleeProject** [comment]
Sorry my bad,
This should be a breaking change...
I'll deprecate 3.2.0 and release 4.0.0

## If you're using vuejs-clipper@3

download 3.1.2 not 3.2.0

## Use build umd file
this is the recommanded way so you don't need to worry about how to build these file.
https://github.com/timtnleeProject/vuejs-clipper#use-dist-files-recommanded

## Upgrade to vuejs-clipper@4, and use dart-sass

use dart-sass (not node-sass) + sass-loader in your project

```bash
yarn add sass sass-loader
```
