### ISSUE TITLE
rounded clip

### ISSUE THREAD

**Issue by dsultanr** [timtnleeProject/vuejs-clipper#119]
is it possible to implement the "round" property to work for the resulting canvas also?

[here are the nice examples from the simple one to complicated](https://stackoverflow.com/questions/1255512/how-to-draw-a-rounded-rectangle-using-html-canvas)

**Comment by dsultanr** [comment]
@timtnleeProject ?

**Comment by timtnleeProject** [comment]
Hi @dsultanr 
## Release v4.1.0
`clipper-fixed`: if prop `round` is `true`, result image will clip in rounded background #119.

###  Demo
https://timtnleeproject.github.io/vuejs-clipper/#/fixed
chose `png` and `round` to see the result.
![image](https://user-images.githubusercontent.com/33143314/145699179-dfbea47d-81cb-4899-b5f1-226fef6cb8f2.png)
![image](https://user-images.githubusercontent.com/33143314/145699204-4ee85e01-5a5c-4c99-a569-1deb2201b5f0.png)

**Comment by dsultanr** [comment]
Excellent. Thanks!

**Comment by dsultanr** [comment]
> chose `png` and `round` to see the result.

@timtnleeProject is it working with the `png` only? I had an unexpected result with this code:

```
canvas.toBlob(function(blob) {
                let fileInputElement = document.getElementById('clipper_result');
                // Here load or generate data
                let data = new Blob();
                let file = new File([blob], "image.jpg",{type:"image/jpeg", lastModified:new Date().getTime()});
                let container = new DataTransfer();
                container.items.add(file);
                fileInputElement.files = container.files;
                // console.log(fileInputElement.files);
            }, 'image/jpeg', 0.8);
```

![image](https://user-images.githubusercontent.com/1683476/147700672-0b6c3f81-3cb5-4f69-ab47-a082a97947e5.png)
![image](https://user-images.githubusercontent.com/1683476/147700680-3e65d9f2-e330-478a-8bb9-b2648e4ed08e.png)

**Comment by timtnleeProject** [comment]
@dsultanr I think jpg will also work but result in the black background.
![image](https://user-images.githubusercontent.com/33143314/148157466-f67615ca-4a5d-482e-a569-49098139fff8.png)
