### ISSUE TITLE
There are no events on resize, zoom, change ratio.

### ISSUE THREAD

**Issue by suenot** [timtnleeProject/vuejs-clipper#14]
Can't find in documentation.

**Comment by timtnleeProject** [comment]
Hi @suenot , what do you mean by resizing?

There's a `onChange$` subject that subscribes to other subjects whatever makes clipping result changes. (zooming and moving subjects)

Usage:

```javascript
mounted () {
  this.$refs.clipper.onChange$.subscribe(() => {
    console.log('onChange')
  })
}
```

However, it's not watching the change of ratio, I'm thinking of adding it.

**Comment by timtnleeProject** [comment]
I've made a [beta version](https://www.npmjs.com/package/vuejs-clipper/v/0.2.12-beta.0) that components will watch ratio change.

**Comment by soloviofff** [comment]
I have tried  beta version 0.2.1-beta.1 t and :ratio="ratioComputed" still don`t work

**Comment by suenot** [comment]
Thanks for reactive answering.  This is a solution that I tried to find: this.$refs.clipper.onChange$.subscribe.

But another problem that mentioned @soloviofff is exist.

**Comment by timtnleeProject** [comment]
I believe the prop `ratio` key binging is working.

> I have tried beta version 0.2.1-beta.1 t and :ratio="ratioComputed" still don`t work,
> I need to change ratio dynamically, and :key seems bad solution

I don't think I understand your question.

Can you be more specific about the scenario?

Thank you :)
