### ISSUE TITLE
Display sizes on preview

### ISSUE THREAD

**Issue by projct1** [timtnleeProject/vuejs-clipper#17]
http://skrinshoter.ru/s/120519/h3IhSFe5

**Comment by timtnleeProject** [comment]
Do you mean the actual size of the preview element (px) or the natural width and height of the clipped image?

**Comment by projct1** [comment]
Natural size of preview for sure (result clipped image)

**Comment by timtnleeProject** [comment]
You can call the component's `getDrawPos` method to get the result position.

```javascript
this.$refs.clipper.getDrawPos().pos
```

it's like

```javascript
{
  sx: 484.3876019690532,
  sy: 274.3328272408713,
  swidth: 951.2248630108757,
  sheight: 531.2248755638097,
  dheight: 531.2248755638097,
  dwidth: 951.2248630108757,
  dx: 0,
  dy: 0
}
```
These value are related to the [`CanvasRenderingContext2D.drawImage()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) parameters.

In this case, sheight(dheight)/swidth(dwidth) are the result's natural height&width.

> p.s. also refer to #18

**Comment by projct1** [comment]
Thanks! But how i can use it dynamically on resize crop area?

**Comment by timtnleeProject** [comment]
```javascript
this.$refs.clipper.onChange$.subscribe(() => {
  this.$nextTick(() => {
    const pos = this.$refs.clipper.getDrawPos().pos
    // ...
  })
})
```

If you are using the `clipper-preview`, `clipper-basic` will call this method and send the position data to the preview component, so you don't need to call that again.

```javascript
this.$refs.clipper.onChange$.subscribe(() => {
  this.$nextTick(() => {
    const pos = this.$refs.preview.pos // get the preview component's property 'pos'
    // ...
  })
})
```

**Comment by projct1** [comment]
@timtnleeProject Ty dude, you just a king 😃
