### ISSUE TITLE
Minimum size of cropped image

### ISSUE THREAD

**Issue by milanP96** [timtnleeProject/vuejs-clipper#19]
Hi! Is it possible to set the minimum size of the cropped image in basic clipper?

**Comment by VladimirLevadnij** [comment]
Hello! I'm interested too!

**Comment by timtnleeProject** [comment]
I made a beta version [0.2.13-beta.1](https://www.npmjs.com/package/vuejs-clipper/v/0.2.13-beta.1).

You could use and test this version.

## 0.2.13-beta.1

### New props

New props for `clipper-basic`: `minWidth` and `minHeight`, represent the minimum width/height(%) of clipping area related to the width/height of the **clipping component**(not source image).

usage:

```html
<clipper-basic
  :minWidth="10"
  :minHeight="10"
></clipper-basic>
```

### clipper-basic will change its layout with the ratio property

If set the `ratio` prop to `clipper-basic`, it will now change its layout ratio too.

See [demo](https://timtnleeproject.github.io/vuejs-clipper/#/basic)(which is using beta version)

**Comment by timtnleeProject** [comment]
Add this feature to v1.0.0
