### ISSUE TITLE
ios 12+ updated src not support

### ISSUE THREAD

**Issue by lasthead** [timtnleeProject/vuejs-clipper#20]
Hi! Thanks for this great component. Very flexible and functional!
But... in IOS i have a problem. After mounted i change src reacting variable, but picture in component doesn't changed.

This problem is seen only on ios devices (10 to 12+ IOS versions). In the desktop browser works correctly

**Comment by timtnleeProject** [comment]
Which browser and version did you use? (like Safari 10?)

I don't have IOS device to test... maybe you could help to find the compacity problem.

**Comment by lasthead** [comment]
Sorry, I found an error and it is not related to your component. I passed a filtered image to the component using canvas, which is not supported in safari

The issue is no longer relevant
