### ISSUE TITLE
 Could you provide src of profile-photo example? 

### ISSUE THREAD

**Issue by tong9977** [timtnleeProject/vuejs-clipper#22]
This is an amazing component that I looking for.
I want to use vuejs-clipper with vuetifly to create customer profie page.
Could you provide src of profile-photo example? 
Thank you

**Comment by timtnleeProject** [comment]
The whole [demo page](https://timtnleeproject.github.io/vuejs-clipper/#/) is on `example` branch.

You can find the profile-photo example at `/src/views/examples/Ex-profile-photo.vue`

## todo: add source references of examples to README

since you're not the only one who asks about this.

**Comment by tong9977** [comment]
ok. Thank you
