### ISSUE TITLE
Adding zoom button (+ / - )

### ISSUE THREAD

**Issue by Afondevi** [timtnleeProject/vuejs-clipper#25]
It's already exist or possible to add button to zoom or unzoom the load picture instead of use scroll (or together)?

**Comment by timtnleeProject** [comment]
`clipper-fixed` can use `setWH$` subject to set the scale.

```javascript
this.$refs.clipper.setWH$.next(1) // set sacle to1
this.$refs.clipper.setWH$.next(1.5) // set sacle to1.5
```

**Comment by Afondevi** [comment]
Ok guy !
I forget this tips :) thanks man
