### ISSUE TITLE
iOS clip() works incorrectly

### ISSUE THREAD

**Issue by lasthead** [timtnleeProject/vuejs-clipper#26]
In safari ios when i tryied cliped image and got incorrect picture
I think this is due to the bug drawImage() in iOs:
https://stackoverflow.com/questions/11929099/html5-canvas-drawimage-ratio-bug-ios

The picture is larger than 2 megabytes incorrectly scaled (drawn) inside the canvas and I can not do anything about it

**Comment by timtnleeProject** [comment]
Hi @lasthead ,
Thanks for finding the problem.

Which IOS version did you use?
If it is possible, could you provide the screenshots related to this issue?

**Comment by timtnleeProject** [comment]
If you're using this solution: [ios-imagefile-megapixel](https://github.com/stomita/ios-imagefile-megapixel)

Maybe you can try this:
```javascript
// methods
load () {
  // listen to clipper's load event @load="load"
  const clipper = this.$refs.clipper
  const canvas = clipper.canvasEl
  const mpImg = new MegaPixImage(canvas)
  mpImg.render(canvas)
  this.$refs.clipper.megapixelImg = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height)
},
clip: function () {
  const clipper = this.$refs.clipper
  const drawPos = clipper.getDrawPos()
  const ctx = clipper.canvasEl.getContext('2d')
  const width = drawPos.pos.swidth // sw
  const height = drawPos.pos.sheight// sh
  clipper.canvasEl.width = width
  clipper.canvasEl.height = height
  ctx.fillStyle = this.bgColor
  ctx.fillRect(0, 0, width, height)
  ctx.translate(drawPos.translate.rotateX, drawPos.translate.rotateY)
  ctx.rotate(this.rotate * Math.PI / 180)
  ctx.translate(drawPos.translate.drawX - drawPos.translate.rotateX, drawPos.translate.drawY - drawPos.translate.rotateY)
  ctx.putImageData(clipper.megapixelImg, 0, 0)
  return clipper.canvasEl
}
```
I don't know if this bug is a rare one (only happens on the old version of iOS?), so I'm not sure whether to put this into component or not.

**Comment by lasthead** [comment]
I checked on the iphone SE device having latest iOS version 12.4. I also checked through xCode simulator on iphone 6S device having iOS 12 version
I think that on earlier versions this problem will also be reproduced.

Here are screenshots from my device. On the first, a small-sized picture is selected and everything is fine with it. The following is a photo with my cat selected and the picture weighs more than 2 megabytes. The third is the result of the clip() method. 
![IMG_2589](https://user-images.githubusercontent.com/43372353/58538093-0e694600-81fd-11e9-8505-f1d9623aaaae.jpg)
![IMG_2590](https://user-images.githubusercontent.com/43372353/58538100-12956380-81fd-11e9-808e-28a19d3e6b02.jpg)
![IMG_2591](https://user-images.githubusercontent.com/43372353/58538107-15905400-81fd-11e9-8c4e-1c36f00cb21e.jpg)

**Comment by timtnleeProject** [comment]
Have you tried the methods above?

**Comment by lasthead** [comment]
Yes, I get a black background without a picture.
Yes, on the desktop i get black background without pictures. maybe the load method is loaded too early?
clipper.canvasEl gives black background

**Comment by timtnleeProject** [comment]
Could you help me try [this](https://timtnleeproject.github.io/vuejs-clipper-issue-repo/issue26/index.html)?

In this page, the result using megapix solution should work.
