### ISSUE TITLE
default ratio: like contain

### ISSUE THREAD

**Issue by suenot** [timtnleeProject/vuejs-clipper#27]
Now default ```ratio``` works like:
```
background-size: cover
```
But in my task I need:
```
background-size: contain
```
https://cssreference.io/property/background-size/

Maybe add a prop ```crop="false"``` or ```auto-position="contain"```?

**Comment by timtnleeProject** [comment]
At `clipper-basic` the image acts like `contain`: _remains fully visible_. when loaded.
So I guess you're asking `clipper-fixed`.

![未命名](https://user-images.githubusercontent.com/33143314/59235931-6012c700-8c26-11e9-9d3b-fe11e910fa48.png)

So you want it acts like B instead of A when loaded?

However `clipper-fixed` can resize images by default so I think it doesn't need to act like `contain`. 
Is there any other reason you need this feature?

**Comment by suenot** [comment]
I tried to calculate zoom, calculate ratio, ratio & zoom… etc. Nothing helped.
At this moment I use a little function to calculate new min-width of clipper (fixed or basic) (I used https://github.com/vorg/fit-rect library):
```js
var target = [0, 0, this.$refs.cropperWrap.clientWidth, this.$refs.cropperWrap.clientHeight]
var rect = [0, 0, this.$refs.clipperFixed.imgEl.naturalWidth, this.$refs.clipperFixed.imgEl.naturalHeight ]
var containedRect = fitRect(rect, target, 'contain')
this.minWidth = containedRect[2]
```

I used ```clipper-fixed```.
![clipper-fixed](https://user-images.githubusercontent.com/1426876/59262966-e6400500-8c48-11e9-9d80-6083255e6e03.png)
and ```clipper-basic```
![clipper-basic](https://user-images.githubusercontent.com/1426876/59262961-e213e780-8c48-11e9-9dde-083236c49ea7.png)
and in both component I need use this function.

Also a good name for this prop is ```fit``` or ```zoom```. For example: ```fit="contain"``` or ```fit="cover"```.

**Comment by timtnleeProject** [comment]
So you want that **when images loaded**, the one axis of the clipping box contains axis of the images?
(A: origin, B: is this you want?)

![未命名](https://user-images.githubusercontent.com/33143314/59316413-f57a8d80-8cf0-11e9-9e94-5050635b7299.png)

Also, I'll fix `clipper-fixed` loaded behavior, now it's like `cover` 
![image](https://user-images.githubusercontent.com/33143314/59316544-a4b76480-8cf1-11e9-9ae1-d88678c7ba91.png)
I'll make it like `contain`
![image](https://user-images.githubusercontent.com/33143314/59316590-d2041280-8cf1-11e9-9263-398f1529868a.png)

By the way, `minWidth` is % related to the wrapped box, so it should be:
```javascript
this.minWidth = containedRect[2]/this.$refs.cropperWrap.clientWidth*100
```
