### ISSUE TITLE
ratioClip and ratioWrap

### ISSUE THREAD

**Issue by suenot** [timtnleeProject/vuejs-clipper#28]
This wonderful plugin needs additional options for clipper-basic /

I have a situation when I need to have a clipper ratio and a clip-area should be different. To prevent the clip-area from going beyond the image
Now there is a prop ratio - which applies to both the clipper and the clip-area
I would like to be able to exhibit various ratio
For example ratioClip and ratioWrap

**Comment by suenot** [comment]
I made this changes in ```method.js```:
```js
  setRatioWH: function ({ width, height, maxWidth, maxHeight, left, top, right, bottom }) {
    if (!this.ratioWrap) return { width, height, left, top, right, bottom }
    // 有設定比例的話進行調整
    const ratioPos = this.ratioPos({ width, height })
    if (ratioPos.x) {
      height = Math.min(width / this.ratioWrap, maxHeight)
      width = (height === maxHeight) ? height * this.ratioWrap : width
    } else {
      width = Math.min(height * this.ratioWrap, maxWidth)
      height = (width === maxWidth) ? width / this.ratioWrap : height
    }
    return { width, height, left, top, right, bottom }
  },
```
in ```clipper-basic.vue```:
```js
props: {
    ratioWrap: {
      type: Number,
      default: NaN
    },
}
```
It almost solved my problem. I don’t understand how to make the clip-area accept the desired ratio from the start. It takes the required ratio at the first resize. But does not accept the new ratio when moving the clip-area. Also, after it has taken a new position, there are problems with moving and resizing.

**Comment by suenot** [comment]
How can I trigger a zoom of clip-area?
After the zoom plugin works as I need.

**Comment by timtnleeProject** [comment]
If clip-area's size is based on/bind to `ratioWrap` property, you can change `ratioWarp` to resize the clip-area in the reactive way.

**Comment by suenot** [comment]
ratioWrap is computed and it doesn`t make effect. I`ll make demo soon

**Comment by suenot** [comment]
https://github.com/suenot/vuejs-clipper-demo/blob/master/src/views/Cropper.vue

**Comment by suenot** [comment]
Need to install packages with yarn, because used yarn workspace for connection with vuejs-clipper package source.

**Comment by suenot** [comment]
All my changes in package I create in separated commit: https://github.com/suenot/vuejs-clipper-demo/commit/d5a42b699d91fed9bb3aca75981a55ec27a8d8b1

**Comment by suenot** [comment]
upd. demo updated. fixed wrong path to demo img

**Comment by timtnleeProject** [comment]
I've made a [beta version](https://www.npmjs.com/package/vuejs-clipper/v/1.0.0-beta.0) at [beta branch](https://github.com/timtnleeProject/vuejs-clipper/tree/beta), this will be the next published version after I update documents and getting feedbacks from you.

I add three new props `wrapRatio`, `initWidth` and `initHeight` for clipper-basic

```html
<clipper-basic 
  :ratio="1/1"
  :warpRatio="4/3"
/>
```

Please look at [demo](https://timtnleeproject.github.io/vuejs-clipper/#/basic) (you might need to release old browser cache to see the new release immediately.) to see how these props work.

I will update the document soon to give a more clear perspective of these props and how clipper-basic works.

**Comment by suenot** [comment]
![Screen Shot 2019-06-14 at 06 00 17](https://user-images.githubusercontent.com/1426876/59480589-dc491c80-8e69-11e9-8573-45efe212148a.png)
this is not expected behaviour. clip area should not move outside clipper.

![Screen Shot 2019-06-14 at 06 03 19](https://user-images.githubusercontent.com/1426876/59480653-216d4e80-8e6a-11e9-9825-f2cba70fed91.png)

**Comment by suenot** [comment]
I'm steel trying to just trigger zoom to engage setRatioWH from method.js :)

**Comment by timtnleeProject** [comment]
You can set `wrapRatio` same as the image's ratio (naturalWidth/naturalHeight), then the clip box would not move outside the area.

**Comment by suenot** [comment]
![Screen Shot 2019-06-14 at 06 09 45](https://user-images.githubusercontent.com/1426876/59480926-123ad080-8e6b-11e9-8764-c353aecfab8f.png)
Thats the main problem, image and clip-area ratio often will be different. In my case.

**Comment by suenot** [comment]
![Screen Shot 2019-06-14 at 06 18 46](https://user-images.githubusercontent.com/1426876/59481284-52e71980-8e6c-11e9-98cd-3862f8f1a789.png)
So sorry, I misunderstand your post. Great! It is solution for my case!

**Comment by suenot** [comment]
I will try it now on my demo.

**Comment by suenot** [comment]
https://github.com/suenot/vuejs-clipper-demo/commit/58222579b2a1b69831d60425008c68ab59a4b9c0
It WORKS! You are amazing!

**Comment by timtnleeProject** [comment]
Great! 👍 
I'll publish it after I update documents, it might take days.

**Comment by timtnleeProject** [comment]
[Version 1.0.1](https://www.npmjs.com/package/vuejs-clipper) published
