### ISSUE TITLE
Image size in cropping area is wrong

### ISSUE THREAD

**Issue by ManuelFrigerio** [timtnleeProject/vuejs-clipper#31]
Hi, thanks for creating this plugin.

I'm creating a simple flow whereby the user uploads an image first and then can click a button to edit it. This button opens a modal, inside which the user can rotate and crop the image using Vuejs-clipper.

I have two problems:

1. If the user uploads a vertical image, the clipping area becomes much bigger of the modal. How do I prevent this? How do I make sure the image is ALWAYS contained within the clipping area and the modal?

2. On mobile, if I use clipped-basic, the image is not contained in the clipping area. Is this by design?

Thansk

**Comment by timtnleeProject** [comment]
Hi @ManuelFrigerio ,
make sure you're using the latest version 1.1.0, `cliper-basic` image will be contained within the area.
>If the user uploads a vertical image, the clipping area becomes much bigger of the modal. How do I prevent this? How do I make sure the image is ALWAYS contained within the clipping area and the modal?

You can set `wrapRatio` props to set the `clipper-basic` container layout ratio.
```html
<clipper-basic
  wrap-ratio="1"
/>
```

**Comment by ManuelFrigerio** [comment]
Hi Tim, I'm using the script in the Zip at `./dist/vuejs-clipper.umd.min.js` 
Is that the version 1.1.0?

**Comment by ManuelFrigerio** [comment]
Also, I keep having the problem on mobile whereby if I upload a photo from my phone, the image is not contained in the clipping area but instead is displayed at full length.

Do you know why this would happen? thanks

**Comment by timtnleeProject** [comment]
**(1) Latest version**

The last commit on Github is the latest code.

Or you can use the NPN CDN script: https://unpkg.com/vuejs-clipper@1.1.0/dist/vuejs-clipper.umd.min.js

If you're using NodeJS:
```bash
npm install vuejs-clipper@latest
```

**(2) Layout only based on width**
Make sure you're styling the clipper by `width` instead of `height`.

**(3) Try demo examples**
https://timtnleeproject.github.io/vuejs-clipper/#/basic
Try this example on your device, is the same problem happen?

If none of the above work, you might need to make a reproduce, thanks 👍

**Comment by ManuelFrigerio** [comment]
Hi Tim, thanks your answer.

I made sure I', using 1.1.0.
However, I'm not sure what you mean by "Make sure you're styling the clipper by width instead of height." Can you elaborate on that please?

The demo works fine on my mobile. Something is wrong.
If you're online in the next hour, you can see my project here: https://a43cbf09.ngrok.io/#create

**Comment by timtnleeProject** [comment]
```html
<clipper class="clipper"/>
```
You can set clipper's width.
```css
.clipper {
  width: 100%;
}
```

However, you cannot set clipper's height
```css
.clipper {
  width: 100%;
  height: 100%;
}
```

This is the limitation of the components, the height is affected by the ratio of the image you upload, or `ratio`, or `wrapRatio`.

Also, be aware that you might not set the height of the clipper but put it in a container element the will affect child elements' height (for example some flexboxes).

**Comment by ManuelFrigerio** [comment]
Hi Tim, I've done that and now the image is contained, however the image is not centred in the clipping area anymore. Any idea why it'd happen?

Also, as I said above your demo works on my mobile but not my website which is an almost identical clone. You can check it out here: https://a43cbf09.ngrok.io/#create
Just upload an image and you'll see another button to edit the image.

Thanks!

**Comment by timtnleeProject** [comment]
I found that some of your css overwrite the origin `.img-scale` element.

![image](https://user-images.githubusercontent.com/33143314/60181199-48595680-9854-11e9-95d7-73c58d8036c5.png)

And I guess you're not using vue-cli right? Because I didn't see any "scoped" style like this (screen shot from my example)
![image](https://user-images.githubusercontent.com/33143314/60181377-a38b4900-9854-11e9-9bfd-e4fbe06e40b0.png)

So be careful of overwriting the component's style.

**Comment by ManuelFrigerio** [comment]
Yes I did that because otherwise the image was completely outside the clipping area.
I didn't use vue-cli. I'm loading the JS from a CDN for this project.

**Comment by timtnleeProject** [comment]
I tried to cancel the style and it worked normally.
![image](https://user-images.githubusercontent.com/33143314/60183611-33cb8d00-9859-11e9-94e3-abdd47d12b26.png)
![image](https://user-images.githubusercontent.com/33143314/60183634-3e862200-9859-11e9-833d-a1e13b95cc4d.png)

**Comment by ManuelFrigerio** [comment]
Hi Tim, thanks! That DID fix it.
Have you tried from mobile? If you upload a photo you just shot, the image is completely off.
Interestingly, this only happens with portrait photos.

Do you know why that happens?

**Comment by timtnleeProject** [comment]
Not only on mobile but also on the PC(resize to the smaller screen).

I'm not found what causes the problem, but other [examples](https://codepen.io/timtnlee/pen/MMEoQb) work fine.

I also found that CDN css DO have scoped css, like
![image](https://user-images.githubusercontent.com/33143314/60225432-66a56d80-98b9-11e9-879c-2cbda857bbcf.png)

So I guess you might accidentally overwrite some of the style of the components.

**Comment by ManuelFrigerio** [comment]
Hi Tim, this shouldn't matter because there is no class with the same name in my website.
I also doublechecked each property of the .clipper element, one by one, and they are identical. 

This is very frustrating :(

**Comment by timtnleeProject** [comment]
Is it possible to make a reproduce?

**Comment by ManuelFrigerio** [comment]
what do you mean?

**Comment by timtnleeProject** [comment]
Try to clone your original app to show how problems happened(in which situation, how did you use it) and put it in a public repository.

Or you could mail me, we can discuss this issue privately, since I think this is a special case.

**Comment by ManuelFrigerio** [comment]
thanks Tim. Agree we can continue privately. I've invited you as collaborator to my git repo :)
