### ISSUE TITLE
clipper-basic component not working after upgrading past version 0.2.13

### ISSUE THREAD

**Issue by travbus** [timtnleeProject/vuejs-clipper#32]
**Describe the bug**
Updated from 0.2.13 to 1.0 also tried 1.1. clipper basic component breaks. was working. clipper fixed works fine. clipper basic console logs 3 errors. If I copy the same code I'm using into the vuejs-clipper examples project the code works fine. which makes me think its to do with my projects dependencies which is just great. Anybody else have this problem? 

1 argument is not a function. Are you looking for `mapTo()`?
    at mapOperation (map.js:7)
2 this.$el.querySelector is not a function
    at VueComponent.mounted (clipper-basic.vue:394)
3 Cannot read property 'width' of undefined
    at VueComponent.posObj (clipper-basic.vue:335)

**Comment by timtnleeProject** [comment]
Have you tried deleting the `node_modules` and re-install again?

```bash
rm -rf node_modules
npm install
```

**Comment by travbus** [comment]
That worked. Thanks. I should have tried that I've had to do it before. Great component!
