### ISSUE TITLE
Set canvas background transparent 

### ISSUE THREAD

**Issue by dwakchaure** [timtnleeProject/vuejs-clipper#33]
When i am cropping image bigger than image then background of remaining portion is white or whatever we have specified in props.

If we can set background transparent then we can use this image in any place without worrying of container background

**Comment by timtnleeProject** [comment]
Hi @dwakchaure ,
is this example fits what you want?
https://timtnleeproject.github.io/vuejs-clipper/#/examples/transparent-bg

**Comment by timtnleeProject** [comment]
```html
<clipper-fixed bg-color="transparent" />
```

**Comment by dwakchaure** [comment]
Hi 
Thanks , i got it now 
sorry i was away couldn't reply
