### ISSUE TITLE
Base64 resizing and downsizing

### ISSUE THREAD

**Issue by emrecanmuslu** [timtnleeProject/vuejs-clipper#35]
Hi,
I have a problem like this, the image I cropped is bigger than the original, how can I solve it?
After cropping 5mb picture it's 18mb.
Sorry for bad english :)

**Comment by timtnleeProject** [comment]
Hi @emrecanmuslu,
are you scaling the image smaller and leave a lot of background like this?
![image](https://user-images.githubusercontent.com/33143314/61169419-8d3cf700-a58f-11e9-8fac-ad6f586d29cb.png)
This will cause the clip image has a very high-resolution though the size is very big.

I'll try to add the feature to limit the size of the pixel of canvas/images.

**Comment by emrecanmuslu** [comment]
Thank you for the answer. I think it would be clearer to share my problem with you as a picture.
1 -> before crop  http://prntscr.com/oeh2kx
2 -> clipped region http://prntscr.com/oeh2px
3 -> after crop http://prntscr.com/oeh3ag
4 -> result http://prntscr.com/oeh3eh
Size increases even if resolution decreases. How can I avoid this problem?

**Comment by timtnleeProject** [comment]
> Size increases even if resolution decreases.

I tried my examples and it doesn't happen.

What's your image type?

Maybe you accidentally transform the `jpeg/jpg` image to `png` image? (This will cause the image size increase)
Remember to specify the image type or it will transform to png.

```javascript
const type = 'image/jpeg'
const quality = 1
const result = canvas.toDataURL(type, quality);
```

**Comment by timtnleeProject** [comment]
After `v1.1.2` clip method can specify the resulting canvas pixel.
See https://github.com/timtnleeProject/vuejs-clipper/wiki/Resulting-canvas-size

**Comment by emrecanmuslu** [comment]
Hi,
Thank you for your help.
I tried the canvas code but it didn't change.
I share with you in more detail. The 670B visually grows 2,100 bytes.

https://drive.google.com/file/d/1HhJ9BTZQSfNH05MC0kITsw-vdv1ip32u/view?usp=sharing

**Comment by timtnleeProject** [comment]
Hi,
make sure you've updated to `^1.1.2`

Also, take a try at this example: https://codepen.io/timtnlee/pen/gVaOrR

the width of the resulting image should be 500pixel.

**Comment by emrecanmuslu** [comment]
After updating my problem is solved. Canvas code worked. Thank you.

**Comment by emrecanmuslu** [comment]
Fixed width works in canvas sizing but maximum width code doesn't work.

https://codepen.io/timtnlee/pen/gVaOrR I set the maximum width to 1024, but it exceeds the size
