### ISSUE TITLE
adding default bootstrap CSS removes the shadow

### ISSUE THREAD

**Issue by mms-** [timtnleeProject/vuejs-clipper#36]
Loading https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css removes shadow from the clipper.

Please see https://codepen.io/anon/pen/PMqemL

**Comment by timtnleeProject** [comment]
Hi, I made a fix with version 1.1.2-beta.1, and it has not been published to the production version yet (will be 1.1.3).

See example: https://codepen.io/timtnlee/pen/gVaOrR

Remember to put vuejs-clipper css after bootstrap css so it won't be override.
