### ISSUE TITLE
Add crossorigin attribute to image. 图片资源请求跨域处理

### ISSUE THREAD

**Issue by LubikLi** [timtnleeProject/vuejs-clipper#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

图片资源请求跨域处理
模板：<div id="imgObj" style="display: none">
    </div>
mounded：
var img = new Image()
    img.crossOrigin = 'anonymous'
    img.src = this.src
    img.setAttribute('crossOrigin', 'Anonymous')
    document.getElementById('imgObj').appendChild(img)

**Comment by timtnleeProject** [comment]
Hi @LubikLi ,
did you mean adding `crossorigin` in the `clipper-basic` & `clipper-fixed` components' image tags?

**Comment by LubikLi** [comment]
Yes. I made a modification to this document. You can compare it. I'm a rookie at the front end, and I'm not sure that's the best way to do it. You can certainly do better. But there are such bugs.


------------------ 原始邮件 ------------------
发件人: "timtnlee"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午5:06
收件人: "timtnleeProject/vuejs-clipper"<vuejs-clipper@noreply.github.com>;
抄送: "lubik"<844916539@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [timtnleeProject/vuejs-clipper] 图片资源请求跨域处理 (#38)



Hi @LubikLi ,
 did you mean adding crossorigin in the clipper-basic & clipper-fixed components' image tags?
