### ISSUE TITLE
How to Change Width of Clip area in clipper-fixed

### ISSUE THREAD

**Issue by leezene** [timtnleeProject/vuejs-clipper#41]
the area class has a inline css with width:50% !important.. what i want is 90% how to change it.

**Comment by timtnleeProject** [comment]
You can use `/deep/` now, but
```css
.clipper-fixed /deep/ .area{
  width: 90% !important;
}
```

chrome will not support `/deep/` in M65
![image](https://user-images.githubusercontent.com/33143314/63008812-e2816680-beb5-11e9-8b2c-4eeb5237a930.png)
![image](https://user-images.githubusercontent.com/33143314/63008841-f927bd80-beb5-11e9-849c-e671f2955ebe.png)

Also, see this [discussion](https://github.com/vuejs/vue-loader/issues/913) if you're using vue-loader

Need time to find a better solution.

**Comment by pranav-xx** [comment]
@timtnleeProject 

Did you find any solution for this?

.clipper-fixed /deep/ .area{
  width: 90% !important;
} 
or ::v-deep is not going to fix this issue as there is an inline style on area element.

**Comment by timtnleeProject** [comment]
Hello, in version `1.1.5`, a new props `area` can set the percentage of width/height of the clip area.

```html
<clipper-fixed :area="60" />
```
