### ISSUE TITLE
Exif-js is only used in component clipper-upload Ios has rotation bugs when I'm using other components

### ISSUE THREAD

**Issue by zss1004504439** [timtnleeProject/vuejs-clipper#42]
**Describe the bug**
Exif-js is only used in component clipper-upload
Ios has rotation bugs when I'm using other components
**To Reproduce**
1. Go to 'Iphone'
2. Click on 'photograph'
 

**Screenshots**
no phone
 

**Smartphone (please complete the following information):** 
 - OS: IOS

**Comment by timtnleeProject** [comment]
> Ios has rotation bugs when I'm using other components

Can you list your steps or provide some screenshots?

**Comment by zss1004504439** [comment]
![image](https://user-images.githubusercontent.com/24915880/63558741-b71b0d80-c580-11e9-83ff-d76367ec8acc.png)
URL: https://timtnleeproject.github.io/vuejs-clipper/#/fixed 
I took photos on my iphone

**Comment by zss1004504439** [comment]
@timtnleeProject 
Notice what I've done in red
Is it the exif-js problem?

**Comment by timtnleeProject** [comment]
@zss1004504439 this page doesn't use `clipper-upload` so it won't process exif image.

**Comment by zss1004504439** [comment]
> @zss1004504439 this page doesn't use `clipper-upload` so it won't process exif image.

I didn't use 'clipper-upload';
Only use 'clipper-basic' to cut the picture on the mobile phone;
Own quote 'exifjs'.
You can think about this situation.

**Comment by timtnleeProject** [comment]
Since `clipper-basic` & `clipper-fixed` only take image URL, they have no data about the image file.

What `clipper-upload` does is transform the original image file to a new orientation canvas then transform the canvas to the URL.

So the exif transformation must done within the step `File => URL`

**Comment by zss1004504439** [comment]
@timtnleeProject thanks
