### ISSUE TITLE
Result image is always png and increase size

### ISSUE THREAD

**Issue by ChristianGiupponi** [timtnleeProject/vuejs-clipper#43]
**Describe the bug**
Following the docs I have copy and paste the example for basic clipper and I have added the `image/jpg` on `canvas.toDataURL`.  
No matter what but the clipper always return a png image that is way big to the original.

Original image:  
example.jpg  
6000x4000  
4.9Mb

Cropped:  
example.png  
3000x1500
5.9Mb

**To Reproduce**
1. Go to https://timtnleeproject.github.io/vuejs-clipper/#/examples/quick-start and copy the full code
2. Upload this image: https://www.pexels.com/photo/photo-of-audi-parked-near-trees-1402787/
3. Crop only the car
4. Download the result image

**Expected behavior**
I expect that the result image is a jpg and the size is lower than the original, not bigger.

**Screenshots**

Original: 
![Schermata 2019-08-22 alle 10 34 39](https://user-images.githubusercontent.com/1614796/63499635-84add980-c4c8-11e9-8a0e-676e71e91135.png)

Cropped:  
![Schermata 2019-08-22 alle 10 34 49](https://user-images.githubusercontent.com/1614796/63499658-8b3c5100-c4c8-11e9-8bf4-d31c982b42ec.png)

**Desktop (please complete the following information):**
 - OS: MacOS and Windows 10
 - Browser chrome

**Comment by timtnleeProject** [comment]
My fault... it should be  `image/jpeg` not `image/jpg`

jpg is an alias of jpeg but it's not a valid mime type.
