### ISSUE TITLE
Nuxt.js support

### ISSUE THREAD

**Issue by 8VAid8** [timtnleeProject/vuejs-clipper#47]
**Describe the bug**
I'm trying to use clipper in a Nuxt.js app. It is throwing errors:
`TypeError: Cannot read property 'left' of undefined
    at VueComponent.translateStyle (vendors.pages_WrappingPaper.js:728)
    at Watcher.get (commons.app.js:16805)
    at Watcher.evaluate (commons.app.js:16910)
    at VueComponent.computedGetter [as translateStyle] (commons.app.js:17160)
    at Object.get (commons.app.js:14409)
    at Proxy.render (vendors.pages_WrappingPaper.js:19023)
    at VueComponent.Vue._render (commons.app.js:15874)
    at VueComponent.updateComponent (commons.app.js:16381)
    at Watcher.get (commons.app.js:16805)
    at new Watcher (commons.app.js:16794)
value @ vendors.app.js:29091
value @ vendors.app.js:29091
value @ vendors.app.js:29091
(anonymous) @ vendors.app.js:29091
push../.nuxt/client.js.vue__WEBPACK_IMPORTED_MODULE_18__.default.config.errorHandler @ app.js:570
globalHandleError @ commons.app.js:14207
handleError @ commons.app.js:14176
Vue._render @ commons.app.js:15876
updateComponent @ commons.app.js:16381
get @ commons.app.js:16805
Watcher @ commons.app.js:16794
mountComponent @ commons.app.js:16399
push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ commons.app.js:20737
init @ commons.app.js:15453
createComponent @ commons.app.js:18300
createElm @ commons.app.js:18247
createChildren @ commons.app.js:18375
createElm @ commons.app.js:18276
createChildren @ commons.app.js:18375
createElm @ commons.app.js:18276
patch @ commons.app.js:18799
Vue._update @ commons.app.js:16271
updateComponent @ commons.app.js:16386
get @ commons.app.js:16805
Watcher @ commons.app.js:16794
mountComponent @ commons.app.js:16399
push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ commons.app.js:20737
init @ commons.app.js:15453
createComponent @ commons.app.js:18300
createElm @ commons.app.js:18247
createChildren @ commons.app.js:18375
createElm @ commons.app.js:18276
createChildren @ commons.app.js:18375
createElm @ commons.app.js:18276
patch @ commons.app.js:18838
Vue._update @ commons.app.js:16274
updateComponent @ commons.app.js:16386
get @ commons.app.js:16805
run @ commons.app.js:16880
flushSchedulerQueue @ commons.app.js:16636
(anonymous) @ commons.app.js:14317
flushCallbacks @ commons.app.js:14243
Promise.then (async)
timerFunc @ commons.app.js:14270
nextTick @ commons.app.js:14327
queueWatcher @ commons.app.js:16728
update @ commons.app.js:16870
notify @ commons.app.js:13069
reactiveSetter @ commons.app.js:13394
proxySetter @ commons.app.js:16957
cropImage @ pages_WrappingPaper.js:1364
invokeWithErrorHandling @ commons.app.js:14191
invoker @ commons.app.js:14516
invokeWithErrorHandling @ commons.app.js:14191
Vue.$emit @ commons.app.js:16214
edit @ pages_WrappingPaper.js:941
invokeWithErrorHandling @ commons.app.js:14191
invoker @ commons.app.js:14516
original._wrapper @ commons.app.js:19239
Show 12 more frames
vendors.app.js:29091 error TypeError: this.$el.querySelector is not a function
    at VueComponent.mounted (vendors.pages_WrappingPaper.js:782)
    at invokeWithErrorHandling (commons.app.js:14191)
    at callHook (commons.app.js:16545)
    at Object.insert (commons.app.js:15474)
    at invokeInsertHook (commons.app.js:18668)
    at VueComponent.patch [as __patch__] (commons.app.js:18887)
    at VueComponent.Vue._update (commons.app.js:16274)
    at VueComponent.updateComponent (commons.app.js:16386)
    at Watcher.get (commons.app.js:16805)
    at Watcher.run (commons.app.js:16880)`
**To Reproduce**
1. Just try to use clipper-fixed

**Expected behavior**
It have to runs without errors

**Comment by 8VAid8** [comment]
I forgot to register component as a plugin and it works now. Sorry.
Plugin code:
`import Vue from 'vue'
import VuejsClipper from 'vuejs-clipper'

Vue.use(VuejsClipper ,{
    　components: {
        clipperBasic: true,
        clipperFixed: true
    　}
    })`

And registration in nuxt.config:
`  plugins: [{ src: '~plugins/vuex-shared-mutations.js', ssr: false }, 
  { src: '~plugins/clipper-plugin.js', ssr: false }],`

**Comment by jahisultan** [comment]
Hi!
I'm currently trying to use vuejs-clipper package in nuxt3 project but it's not working well.
Can you help me?
