### ISSUE TITLE
Uses es6.Promise polyfill that overrides es7.promise.finally polyfill

### ISSUE THREAD

**Issue by markRosenvinge** [timtnleeProject/vuejs-clipper#48]
**Describe the bug**
When using the package on browsers that requires the Promise Polyfill the current use of es6.promise polyfill overrides usage off the es7.promise.finally polyfill, which makes other code that depends of it break.

the promise.finally method is used more and more in other packages, that fails when used together with this package.

**To Reproduce**
1. Go to any page that includes this package and has another package that uses the promise.finally polyfill.
2. See error in console complaining that promise.prototype.finally does not exists (since it has been overriden)

**Expected behavior**
The Promise polyfill should not override the es7.promise polyfill if it is allready present.

**Screenshots**
![image](https://user-images.githubusercontent.com/12033944/65173867-09e8c780-da50-11e9-9685-9917b89178bb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] IE11

**Smartphone (please complete the following information):**

**Additional context**
By removing the promise polyfill from this package the issue no longer occures. The correct solution would be to make the 2 poilyfills not override.

**Comment by timtnleeProject** [comment]
I didn't add any polifill, it's all @vue/cli config by nature
any suggestion?
