### ISSUE TITLE
TypeError in clipper basic component

### ISSUE THREAD

**Issue by VictorOnwukwe** [timtnleeProject/vuejs-clipper#49]
**Describe the bug**
Every time the clipper basic component is rendered I get this error: "TypeError: Cannot read property 'width' of undefined"

This is the line where the error generates in the clipper-basic component.
//'width': `${this.zoomWH$.width}% !important`,

Apparently zoomWH$ is undefined. It generates this error for the width and height. When I manually set the width and height props, i.e
//'width': `"50%" !important`
//'height': `"50%" !important`

I load the image. Then a new error occurs: "TypeError: Cannot read property 'next' of undefined"

**Desktop (please complete the following information):**
 - windows10
 - chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by timtnleeProject** [comment]
This might because of you didn't register/install `vue-rx` correctly

**Comment by VictorOnwukwe** [comment]
> This might because of you didn't register/install `vue-rx` correctly

Wow. Thanks a lot... It's working fine now.

Thanks too, for such awesome contribution. It's helped me to a large extent
