### ISSUE TITLE
separately import components with non vue-rx

### ISSUE THREAD

**Issue by matamune94** [timtnleeProject/vuejs-clipper#50]
how can do that ?

**Comment by timtnleeProject** [comment]
These components are based on `vue-rx`, using it's subscription hook, so I can't import them without `vue-rx`

**Comment by matamune94** [comment]
ok , how i can change size clipping box with clipperFixed ?

**Comment by timtnleeProject** [comment]
#41 
This is the temporary solution.

**Comment by matamune94** [comment]
not working sir

**Comment by timtnleeProject** [comment]
off topic, the second question is duplicated to #41
