### ISSUE TITLE
h5 use take photo image the orientation bug

### ISSUE THREAD

**Issue by ZarCool** [timtnleeProject/vuejs-clipper#52]
**Describe the bug**
hi timtnlee, pictrue orientation not right when i use vuejs-clipper in my h5, the picture was takephoto producted
(
  你好，当我使用vue-clipper在我h5中时，遇到选择拍照后的照片，生成出来的图片方向不对的情况，
我猜想是因为生成图片的时候没有读取图片的原始方向信息。我找到exif-js这个库可以解决问题，但是我不知道怎样集成进这个项目
)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timtnleeProject** [comment]
Hi, @ZarCool 
use [clipper-upload](https://github.com/timtnleeProject/vuejs-clipper#clipper-upload) will automatically transform the orientation of the image.

[Example](https://timtnleeproject.github.io/vuejs-clipper/#/basic) using clipper-upload.

If you want to implement yourself you can refer the source code of `clipper-upload`.

**Comment by ZarCool** [comment]
Awesome solution！thanks！！: )
