### ISSUE TITLE
clipper-upload doesn't work in android web view.

### ISSUE THREAD

**Issue by smirkkk** [timtnleeProject/vuejs-clipper#53]
clipper-upload doesn't work in android web view.
There is no error message, just no action even click clipper-upload component.
(I guess iOS web view too)
But It works in mobile chrome browser. 
Can I solve this problem?

**Comment by timtnleeProject** [comment]
Hi @smirkkk it works on my andriod phone,
could you try [this example](https://timtnleeproject.github.io/vuejs-clipper/#/basic) on your webview to see if the uploader works?
