### ISSUE TITLE
Disable wheel event

### ISSUE THREAD

**Issue by benben994** [timtnleeProject/vuejs-clipper#54]
Hi I'm wondering is there any way that I can disable only wheel event for zooming?
I saw the onChange$ subscribe all resize, rotate event.
But I only need to prevent user to use mouse wheel.
Thanks.

**Comment by timtnleeProject** [comment]
Hi @benben994 ,
I'm afraid not, zooming by wheel is the natural feature of `clipper-fixed`, and should not be disabled.
You can use `clipper-basic` instead.

**Comment by UnderTheMoonspell** [comment]
This option would be really nice. I need all the features of clipper-fixed but I just want to prevent zooming with the mouse wheel, I tried to capture the wheel event and use preventDefault but it doesnt work

**Comment by timtnleeProject** [comment]
## New feature in the next version

Add a prop `handleZoomEvent` to intercept both mouse and touch zooming events.

Example:

```html
<clipper-fixed :handleZoomEvent={handleZoomEvent}/>
```

```javascript
// method
handleZoomEvent: function (scale) {
  // normal behavior
  return scale;
  // disable zoom
  return NaN;
}
```

**Comment by UnderTheMoonspell** [comment]
@timtnleeProject thank you so much. Awesome plugin!

**Comment by timtnleeProject** [comment]
v3.0.3 released
