### ISSUE TITLE
$attrs is readonly and  $listeners is readonly

### ISSUE THREAD

**Issue by ftpyz** [timtnleeProject/vuejs-clipper#56]
**Describe the bug**
i use this component in nuxtjs. i register with

import Vue from "vue";
import VuejsClipper from "vuejs-clipper";

Vue.use(VuejsClipper, {
  components: {
    clipperBasic: true,
    clipperFixed: true,
    clipperPreview: true,
    clipperUpload: true
  }
});

and add my nuxt.config.js

{ src: "~/plugins/clipper", ssr: false }

i use with component static data. but i change data static generate error.

**Comment by timtnleeProject** [comment]
Hi @ftpyz ,
could you make more details about
`i use with component static data. but i change data static generate error.`.

I create a Nuxt app and use the plugin but don't know how to reproduce the error.

**Comment by timtnleeProject** [comment]
close due to no reply
