### ISSUE TITLE
clipper-fixed ratio property not working on edge

### ISSUE THREAD

**Issue by Panksi** [timtnleeProject/vuejs-clipper#57]
clipper-fixed ratio property is not working on edge

I have a setup like this
```
<clipper-fixed
              ref="clipper"
              :src="imgSrc"
              :ratio="'3/4'"
              :area="70"
              :rotate="rotationAngle">
            </clipper-fixed>
```
and ratio is not even close to 3/6, see example **but make sure to open up in EDGE**:
[https://codepen.io/panksi/pen/mdJomLZ](https://codepen.io/panksi/pen/mdJomLZ)

on firefox and chrome, it works
furthermore, I think its the polyfills but it doesn't work in internet explorer at all. My next app won't start up when loading the app in IE

**Comment by timtnleeProject** [comment]
Hi @Panksi ,
ratio should be number like
```html
<clipper-fixed :ratio="3/4"></clipper-fixed>
```
Also my edge works fine: (ratio: 2)
![image](https://user-images.githubusercontent.com/33143314/78090787-b2afb080-73fd-11ea-9512-ce1bbabf3705.png)

**Comment by Panksi** [comment]
@timtnleeProject Sorry for my late answer, 
And sorry for false alarm, it definitely works on edge, it's just that in edge preview on codepen is not refreshed automatically when you change something in code. anyhow thanks for the update

**Comment by Panksi** [comment]
@timtnleeProject Hello again,
I think I figured out whats the problem:
this is the chrome view:
![image](https://user-images.githubusercontent.com/16855132/78893874-5affed80-7a6c-11ea-8b50-e4f4e727573c.png)

and this is the edge/IE view:
![image](https://user-images.githubusercontent.com/16855132/78893959-81258d80-7a6c-11ea-8e9b-ee9b65ea3c7e.png)


and this happens because I set the height: 100%; on clipper component.
If I don't do that this happens in all browsers:
![image](https://user-images.githubusercontent.com/16855132/78894145-dbbee980-7a6c-11ea-863e-18b7955c99e2.png)


and at the end, I think its the calculation of canvas element which Is making the problem:
![image](https://user-images.githubusercontent.com/16855132/78894305-1a54a400-7a6d-11ea-99cf-b8335e2694e3.png)

**because my ratio is 3/4**.
so the ratio is being reflected not only on stem-area canvas but stem-outer also:
![image](https://user-images.githubusercontent.com/16855132/78894548-8931fd00-7a6d-11ea-97de-cc29ab2c1dce.png)

**Comment by timtnleeProject** [comment]
Maybe try not to set height,
instead of using wrapRatio?
Reference here:
https://github.com/timtnleeProject/vuejs-clipper/wiki/Component-layout
https://github.com/timtnleeProject/vuejs-clipper/wiki/Component-layout-in-depth

**Comment by Panksi** [comment]
@timtnleeProject thanks for the suggestion, however, I "hacked" it already so it works now. It's not the happiest solution, but it works.

wrapRatio is a good solution if you don't want the component to be responsive, but as soon as you have different height and width ratio for mobile and tablet devices you are basically stuck with coding the ratios for different viewports in VUE component, and I don't think that's the best practice. I personally want to have a responsive design controlled by css where it belongs. 

anyhow I will close this again because it's not relevant anymore...
