### ISSUE TITLE
clipper-basic and clipper-preview sync bug

### ISSUE THREAD

**Issue by davidww2** [timtnleeProject/vuejs-clipper#60]
Hi
**Describe the bug**

I use clipper-basic and clipper-preview and There is a bug with the sync the image position
I tried in other components and remove and install again
But the problem didn't fix

**My Code**
```
<clipper-upload v-model="Imgs[0]" @input="getFileName()"
              ><el-button type="primary"
                >upload photo
              ></el-button>
            </clipper-upload>

<clipper-preview name="fixed-preview">
              <h2 slot="placeholder" style="text-align: center;">no photo</h2>
            </clipper-preview>

<clipper-basic
            :src="Imgs[0]"
            bg-color="black"
            :round="false"
            preview="fixed-preview"
            shadow="rgba(0,0,0,0)"
            ref="clipper"
            :init-width="100"
            :init-height="100"
          ></clipper-basic>
```

Everything was good until yesterday
Can you fix the bug or help me how to fix it?

**Screenshots**
[Orginal](https://imgur.com/uPSofZt)
[Clippers](https://imgur.com/ux2koKW)
[Result](https://imgur.com/QvsqwoS)

**Device -  Desktop**
 - Browser [e.g. Chrome 81 on Windows 10]

Thank you

**Comment by timtnleeProject** [comment]
Hi, you can reference the `examples` branch,
I've update the `vue` and `vuejs-clipper`, and everything works.
Did you have more information or any error in console?
