### ISSUE TITLE
Prefix css class names

### ISSUE THREAD

**Issue by asbiin** [timtnleeProject/vuejs-clipper#61]
**Is your feature request related to a problem? Please describe.**
I'm using [purgecss](https://laravel-mix.com/extensions/purgecss) in my project to reduce css file size. It can whitelist some css class, using regex patterns.

**Describe the solution you'd like**
To allow purgecss use, use the same pattern on all css class names. The idea is to use the same prefix on every class.

See use of vuejs-clipper [here](https://github.com/monicahq/monica/pull/3942)

**Comment by timtnleeProject** [comment]
Hi @asbiin ,
I would like to change the naming to BEM at v3.0,
for style classes will be the format as `vuejs-basic__xxx`.
For the DOM selector class will be `js-xxx`.

**Comment by timtnleeProject** [comment]
v2.0 prefix will be `vuejs-clipper-basic__` and `vuejs-clipper-fixed__`
