### ISSUE TITLE
White canvas after call clip()

### ISSUE THREAD

**Issue by igorpopryadukhin** [timtnleeProject/vuejs-clipper#63]
**clipper-fixed** white canvas after call clip()

`
<clipper-fixed
            ref="avatar_clipper"
            :src="imgDataUrl"
            border-color="white"
            corner
            round
            border="4"
            style="height: 350px"
            grid
            wrap-ratio=""
          />

...
const canvas = this.$refs.avatar_clipper.clip()
this.avatar = canvas.toDataURL(this.file_avatar_type, 1) // white canvas (
this.avatar_clipper = false 
`

![image](https://user-images.githubusercontent.com/48174353/85076432-c7b00a80-b1c8-11ea-88d7-c82b3ad0b2bc.png)

However, if "clipper-fixed" change to "clipper-basic" everything works fine

Out data
`data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAExATEDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAr/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//Z`

**Comment by timtnleeProject** [comment]
Hi @igorpopryadukhin ,
which version did you use?

Could you re-produce on codesandbox or codepen?

**Comment by igorpopryadukhin** [comment]
I realized what the problem is.

The problem arises if you do not use `clipper-preview`
But I didn’t need `clipper-preview`
I tried to hide it
  `<clipper-preview
             name = "clipper-preview"
             style = "display: none"
           /> `

But it did not work, everything is exactly a white canvas.


It turns out that it works only with `clipper-preview`

Sorry, used google translate

**Comment by timtnleeProject** [comment]
It looks fine for me,
just make an example here:
https://codesandbox.io/s/distracted-sunset-8cspi?file=/src/App.vue

**Comment by igorpopryadukhin** [comment]
Sorry, 

old
`
<clipper-fixed 
      ...
      border="3"
      ...
/>
`
Error in console and white canvas.

new
`
<clipper-fixed 
      ...
      :border="3"
      cross-origin="anonymous" // New line
      ...
/>
`
No error console and my photo in canvas.

The problem is in "border"

Best "border = number"
Bad "border = string"


Sorry, I not speak English.
Although maybe a few phrases I wrote without a translator

Thanks' you
