### ISSUE TITLE
Shifted canvas in Firefox

### ISSUE THREAD

**Issue by l4ngur** [timtnleeProject/vuejs-clipper#65]
**Describe the bug**
The canvas is shifted in Firefox 78 (linux), when vertically oriented photo (height > width) is uploaded and ratio option is enabled. The clipped image does not match the selected area also.

**To Reproduce**
1. Go to https://timtnleeproject.github.io/vuejs-clipper/#/basic with Firefox.
2. Upload vertically oriented photo
3. Select any ratio
4. See shifted canvas

**Screenshots**
![screenshot-timtnleeproject github io-2020 07 22-15_56_49](https://user-images.githubusercontent.com/3416571/88186326-546d3e80-cc35-11ea-8e42-de187312ca6f.png)

Ratio disabled - expected behavior:
![screenshot-timtnleeproject github io-2020 07 22-15_56_10](https://user-images.githubusercontent.com/3416571/88186424-6fd84980-cc35-11ea-86eb-a5774134cae0.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser: Firefox
 - Version: 78.02

**Comment by timtnleeProject** [comment]
It has some issues with Firefox for displaying vertical based boxes.
I've made a quick fix and push to the example pages:
see https://timtnleeproject.github.io/vuejs-clipper/#/basic with Firefox, it should fix.

I'll make a new release soon.

**Comment by l4ngur** [comment]
I confirm that it is fixed. Thank you for fast response and I am looking forward to a new release.
