### ISSUE TITLE
Clipping wrong area after rotating the picture

### ISSUE THREAD

**Issue by aNyMoRe0505** [timtnleeProject/vuejs-clipper#66]
**Describe the bug**
clipping wrong area after rotating the picture

**To Reproduce**
1. Go to https://timtnleeproject.github.io/vuejs-clipper/#/basic
2. rotate image
3. drag clipping area
4. See preview block

**Screenshots**
<img width="1148" alt="截圖 2020-07-30 下午6 19 21" src="https://user-images.githubusercontent.com/9814815/88912046-45b80480-d291-11ea-9e9a-83549614a38d.png">

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 2.1.1

**Comment by timtnleeProject** [comment]
fix on 2.1.2
