### ISSUE TITLE
Height of the resultant canvas is always 1 less than it should be

### ISSUE THREAD

**Issue by xploSEoF** [timtnleeProject/vuejs-clipper#68]
**Describe the bug**
The height of the canvas element produced by the clip() method is always 1 less than it should be.

**To Reproduce**
1. Have a ratio of "1", "2", or something equally simple.
2. When clipping, clip to something simple using width, I've picked "100"
3. Console debug the result of the clip function, and take note of the canvas size

**Expected behavior**
I expect the width and height to be the same when I have a ratio of "1". Likewise, when having an ratio of 2, I expect the height to be half the width.

**Comment by timtnleeProject** [comment]
@xploSEoF I found that there's bug initializing the ratio clip-area, if you drag a new clip-area the result is correct.

I'll make a fix on v3.0.1

**Comment by francoguilherme** [comment]
@timtnleeProject This is still happening to me. Depending on the size of the component, sometimes the canvas height is correct, sometimes is 1px or 2px less. Could this be a problem with ratio rounding errors? I'm using some weird ratios like 300/169 and 420/140. Is it possible to add a _hPixel_ property to the clip options to force the height as well?

**Comment by timtnleeProject** [comment]
Hi @francoguilherme 
See this:
https://github.com/timtnleeProject/vuejs-clipper/issues/80#issuecomment-724570277
If you really want to get pixel precisely, try to set the clipper width as the same pixel as your image's natural pixel.
