### ISSUE TITLE
Clipper-classic ignore ration on init

### ISSUE THREAD

**Issue by mrquokka** [timtnleeProject/vuejs-clipper#71]
**Describe the bug**
If i set ratio to "1" and open image like 400x700, ratio of selected ignored(it will be 4:7)

**To Reproduce**
`<clipper slot="content" :src="loaded_image" ref="clipper" :ratio="1" />`

**Expected behavior**
init_size need to 50px x 50px*ratio or somethink another

**Screenshots**
https://ibb.co/XSpW9RS

**Desktop (please complete the following information):**
Ubuntu 20.04, Chrome 85

**Comment by timtnleeProject** [comment]
Hi @mrquokka ,
thanks for reporting this issue.

The root cause is that the component did not reset position correctly (should reset in the $nextTick).

This will be fixed on v3.0.2

**Comment by mrquokka** [comment]
> Hi @mrquokka ,
> thanks for reporting this issue.
> 
> The root cause is that the component did not reset position correctly (should reset in the $nextTick).
> 
> This will be fixed on v3.0.2

@timtnleeProject, thanks checked and problem now resolved
