### ISSUE TITLE
Clipper-upload Wrong Orientation 

### ISSUE THREAD

**Issue by UnderTheMoonspell** [timtnleeProject/vuejs-clipper#73]
**Describe the bug**
When I upload a vertical photo taken from my Xiao Mi 9T the photo is rotated 90 degrees, if done through the example page https://timtnleeproject.github.io/vuejs-clipper/#/fixed, which doesnt use clipper-upload the image is correctly uploaded

**To Reproduce**
1. Upload a vertical photo with clipper-upload

**Expected behavior**
Image should be vertical but its rotated 90 degrees.

**Desktop (please complete the following information):**
 - OS: MacOs, Android
 - Browser Chrome

**Additional context**
This is the metadata of the image

ExifTool Version Number         : 10.80
File Name                       : tmp_9fa24fe47557c7efb09370e2fb8f1fd34067255a.jpg
File Size                       : 5.7 MB
File Modification Date/Time     : 2020:09:15 12:04:51+02:00
File Access Date/Time           : 2020:09:15 12:04:51+02:00
File Inode Change Date/Time     : 2020:09:15 12:04:51+02:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Camera Model Name               : Mi 9T
Orientation                     : Rotate 270 CW
Modify Date                     : 2020:09:15 11:01:39
Y Cb Cr Positioning             : Centered
ISO                             : 176
Exposure Program                : Program AE
F Number                        : 2.2
Exposure Time                   : 1/100
Sensing Method                  : Not defined
Sub Sec Time Digitized          : 288216
Sub Sec Time Original           : 288216
Sub Sec Time                    : 288216
Focal Length                    : 3.5 mm
Flash                           : Off, Did not fire
Light Source                    : D65
Metering Mode                   : Center-weighted average
Scene Capture Type              : Standard
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Focal Length In 35mm Format     : 18 mm
Max Aperture Value              : 2.2
Create Date                     : 2020:09:15 11:01:39
Exposure Compensation           : 0
Exif Image Height               : 3880
White Balance                   : Auto
Date/Time Original              : 2020:09:15 11:01:39
Brightness Value                : 3.34
Exif Image Width                : 5184
Exposure Mode                   : Auto
Aperture Value                  : 2.2
Components Configuration        : Y, Cb, Cr, -
Color Space                     : sRGB
Scene Type                      : Directly photographed
Shutter Speed Value             : 1/100
Exif Version                    : 0220
Flashpix Version                : 0100
Resolution Unit                 : inches
X Resolution                    : 72
Y Resolution                    : 72
Make                            : Xiaomi
Thumbnail Offset                : 3085
Thumbnail Length                : 13420
Compression                     : JPEG (old-style)
Image Width                     : 5184
Image Height                    : 3880
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.2
Image Size                      : 5184x3880
Megapixels                      : 20.1
Scale Factor To 35 mm Equivalent: 5.1
Shutter Speed                   : 1/100
Create Date                     : 2020:09:15 11:01:39.288216
Date/Time Original              : 2020:09:15 11:01:39.288216
Modify Date                     : 2020:09:15 11:01:39.288216
Thumbnail Image                 : (Binary data 13420 bytes, use -b option to extract)
Circle Of Confusion             : 0.006 mm
Field Of View                   : 90.0 deg
Focal Length                    : 3.5 mm (35 mm equivalent: 18.0 mm)
Hyperfocal Distance             : 0.96 m
Light Value                     : 8.1

**Comment by timtnleeProject** [comment]
Hi @UnderTheMoonspell 
`clipper-upload` will transform **exif** image orientation by default.
You can set `:exif="fale"` to disable this behavior.

**Comment by UnderTheMoonspell** [comment]
@timtnleeProject once again thanks, I had tried it and it didnt work, but I have three clipper-uploads and I added the property to the hidden one. Yes I tried it now again and it works
