### ISSUE TITLE
Why this error occurs

### ISSUE THREAD

**Issue by xiangyuisabatman** [timtnleeProject/vuejs-clipper#74]
**Describe the bug**
An error will be reported after starting the project

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/23613080/93730629-05736380-fbfc-11ea-9b4b-b777f9bd41fd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timtnleeProject** [comment]
Did you have css-loader like `node-sass` installed and config correctly?

**Comment by xiangyuisabatman** [comment]
![image](https://user-images.githubusercontent.com/23613080/93750729-89464380-fc2e-11ea-8f21-822810e45f7f.png)
webpack config
![image](https://user-images.githubusercontent.com/23613080/93750886-cca0b200-fc2e-11ea-85c5-9cbac8a7d256.png)

**Comment by timtnleeProject** [comment]
Not sure but might related to
https://github.com/postcss/postcss-cli/issues/199
https://github.com/stylelint/stylelint/issues/3943

Maybe try to update postcss and it's deps

**Comment by timtnleeProject** [comment]
Also, you can use vuejs-clipper build files so you don't need css pre-processor to compile (Which did not be mentioned in doc but should be).

```javascript
import Vue from "vue";
import VueRx from "vue-rx";
// Use build files
import VuejsClipper from "vuejs-clipper/dist/vuejs-clipper.umd";
import "vuejs-clipper/dist/vuejs-clipper.css";

Vue.use(VueRx);
Vue.use(VuejsClipper);
```

**Comment by xiangyuisabatman** [comment]
ok,i try,thanks.
