### ISSUE TITLE
After cropping image with clipper-fixed, how to get the cropped image source

### ISSUE THREAD

**Issue by diswarJitesh** [timtnleeProject/vuejs-clipper#76]
I am uploading an image with clipper-upload and showing it in clipper-fixed. I am adjusting image in clipper-fixed, how can i get that particular clipped image source.

**Comment by timtnleeProject** [comment]
Hi @diswarJitesh 
You can use the canvas or transform canvas to image.
https://timtnleeproject.github.io/vuejs-clipper/#/examples/canvas-to-image
