### ISSUE TITLE
Add scale with v-model binding for clipper-fixed

### ISSUE THREAD

**Issue by rbloone** [timtnleeProject/vuejs-clipper#79]
Problem: I want to change the scale/zoom of the fixed clipper using the <clipper-range> component.

Solution: Add prop to clipper-fixed component with could be used together with the v-model attribute.

**Comment by timtnleeProject** [comment]
Hi @rbloone 
You can use `handle-zoom-event` and `setWH$`(rxjs Subject) to make `v-model` like feature.
https://codesandbox.io/s/clipper-fixed-scale-control-p8ovc?file=/src/App.vue

**Comment by rbloone** [comment]
Thank you for your answer and for the sandbox too.

**Comment by rbloone** [comment]
Would be nice to have props defining min/max zoom value to match with <clipper-range> component props.

Now zooming with the mouse is not limited. But for the range component, you should specify min/max values.

https://codesandbox.io/s/clipper-fixed-scale-control-forked-u52z5

**Comment by timtnleeProject** [comment]
Hi @rbloone ,
There might be a work around, you can control mouse scaling in `handle-zoom-event`
for example:
```javascript
handleZoom(scale) {
  // maximum: 2, minimal: 0.1
  const limitedScale = Math.max(Math.min(2, scale), 0.1);
  this.scale = limitedScale;
  return limitedScale;
}
```
