### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by dewita** [timtnleeProject/vuejs-clipper#8]
Hi !

I'm using the clipper-fixed component to do my stuff but i get the error as written in the title.

This is related to that [thread](https://www.chromestatus.com/features/6662647093133312).

can you help me ? :)

**Comment by dewita** [comment]
As you can see, I have the same problem with your examples.

<img width="1920" alt="error_case" src="https://user-images.githubusercontent.com/26024628/54998060-7c12af00-4fcd-11e9-93ad-ed6a45841b93.png">

**Comment by timtnleeProject** [comment]
Hi @dewita ,
thanks for this important information.
We need to use passive events for a better scrolling experience.

I use it on `touch` events but missing the `wheel` event.

Here's where I define window wheel event (`src\components\extends\clippo.js`)

## Original

```javascript
const rxWheelListeners = {
  beforeCreate() {
    this.wheel$ = fromEvent(window, 'wheel')
  }
}
```

## Will be fixed at next version

```javascript
const rxWheelListeners = {
  beforeCreate() {
    this.wheel$ = fromEvent(window, 'wheel', { passive: false })
  }
}
```

**Comment by dewita** [comment]
Seems clear !

Thanks for your maintenance @timtnleeProject
