### ISSUE TITLE
Image is not placed in the center in firefox if requested ratio is bigger than image ratio

### ISSUE THREAD

**Issue by juli-p** [timtnleeProject/vuejs-clipper#82]
**Describe the bug**
I ran into a problem with the basic clipper component: The selected image is placed incorrectly onto the canvas if a ratio bigger than the ratio of the selected image is set. If e.g. a photo with an aspect ratio of 4:3 is selected and I try to set a fixed ratio for the clipper of 4:1 I can not see the image anymore because it seems to be placed too far to the left (if zoomed out completely you can usally find it again). The problem does not show up if a smaller ratio is selected than the original image has.
I only experienced the problem with firefox but not with chromium so I assume it has to do with browser compatibility.

**To Reproduce**
1. include a basic clipper component
2. use firefox 76.0 on fedora
2. select an image to crop
3. set the ratio prop > than the image aspect ratio

**Expected behavior**
The expected behaviour obviously would be that the image position is not related to the selected fixed ratio value as it can be seen in chromium.

**Screenshots**
![vue-clipper bug](https://user-images.githubusercontent.com/63345753/100540691-11545500-323f-11eb-91f7-ebfd7527a9d1.png)
(zoomed out to show that image is still there but placed incorrectly)

**Desktop (please complete the following information):**
 - OS: fedora
 - Browser firefox
 - Version  76.0 64-bit

**Comment by timtnleeProject** [comment]
Hi @juli-p ,
thanks for report this issue.
I have released `v3.1.1` to fix this issue.

![image](https://user-images.githubusercontent.com/33143314/100839796-cbea8e80-34af-11eb-844b-77433551f0aa.png)
