### ISSUE TITLE
No possibility to set ratio in px :(

### ISSUE THREAD

**Issue by AlexanderWM** [timtnleeProject/vuejs-clipper#84]
It is a pity that it is impossible to set the size of the frame accurately. For example, if I need a 212x352 image, I have no way to select it.

**Comment by timtnleeProject** [comment]
> It is a pity that it is impossible to set the size of the frame accurately. For example, if I need a 212x352 image, I have no way to select it.

Hi @AlexanderWM ,
The size of the clip box can be zoom-in and out,
so in my opinion it's reasonable that it cannot be fixed at a particular size.
