### ISSUE TITLE
The cropped image takes up 5 times more space

### ISSUE THREAD

**Issue by Manfies** [timtnleeProject/vuejs-clipper#88]
**Describe the bug**
The cropped image takes up 5 times more space than the original image.

**To Reproduce**
1. Go to https://timtnleeproject.github.io/vuejs-clipper/#/fixed
2. Upload new file (for me it was 3840x2160 - 344K)
3. Crop and download result file
4. Image takes 1.4M 0_o

**Expected behavior**
Smaller, the same or slightly larger size of the final image. Here the increase is almost 5 times.

**Screenshots**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/9979526/102766467-3b58ed00-438f-11eb-9765-80cffedd8653.png">

**Desktop:**
 - OS: MacOS
 - Browser: Mozilla Firefox
 - Version: 84.0

**Comment by timtnleeProject** [comment]
Hi @Manfies ,
> To Reproduce
> Steps to reproduce the behavior:
>
> 1. Go to https://mail.google.com/mail/u/1/#inbox/FMfcgxwKjxBlGdvcwmbnpVFzCMpKHVSD
> ...

sorry that I don't see what you mean, why you gave me the Gmail link?

If this the issue related to https://github.com/timtnleeProject/vuejs-clipper/wiki/Resulting-canvas-size ?

**Comment by Manfies** [comment]
Hi @timtnleeProject, oh yeah, sorry. I have updated a link.
But yes, it's related with Resulting canvas size, thank you. It solved my issue.
Also i have a qustion about clipper-fixed, I just don't know where to ask.

For example i am using clipper-fixed on the page and clipping image with size 3000x2000 px.
I use ration 1/1 for clip-area, and I need minimum size of result image 1500x1500 px for example. That is, I need to disable zooming when the area is less or equal than 1500px.vI don't know how to implement it because there aren't any options for this. Thanks!

**Comment by timtnleeProject** [comment]
1. To limit the size of zooming, use [min-scale](https://github.com/timtnleeProject/vuejs-clipper#clipper-fixed)
```javascript
<clipper-fixed :min-scale="1" />
```
2. To limit the resulting canvas pixel, use `clip({ maxWPixel })`

3. If you want the image sizing limit to actually `1500px`, you need to get the origin image size (when the image on-load or use clipper data) and calculate the `min-scale` by yourself.

Possible example:

```javascript
computed: {
  minScale () {
    return 1500 / (this.$clipper.imgEl?.naturalWidth || 1)
  }
}
```
