### ISSUE TITLE
Error happens when importing module (UnhandledPromiseRejectionWarning)

### ISSUE THREAD

**Issue by developeralp** [timtnleeProject/vuejs-clipper#89]
I'm trying to install the library. It occurs when I import.

**To Reproduce**
1. npm install -D sass-loader node-sass
2. npm install vuejs-clipper --save
3. npm install vue-rx rxjs --save
4. Import VueRx and VuejsClipper 
5. Import as 'vuejs-clipper soruce'

**Expected behavior**
Webpack builds smoothly.

**Desktop**
 - OS: Windows 10 Home
 - Browser: Google Chrome 87.0.4280.88
 - Version: 3.1.1

`(node:8992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8) 49% building modules 332/336 modules 4 active ...er\src\components\clipper-preview.vue `

```
(node:8992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:8992) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

```

**Comment by timtnleeProject** [comment]
Hi @developeralp ,
refer to the [installation guide](https://github.com/timtnleeProject/vuejs-clipper#installation-npm--esm),
could you provide more detailed information about your setup?

**Comment by developeralp** [comment]
Hello,

Thanks for your fast response.

I have these modules installed already:
```
 "dependencies": {
    "jquery": "^3.5.1",
    "prettier": "^2.1.2",
    "rxjs": "^6.6.3",
    "vue": "^2.5.2",
    "vue-cookies": "^1.7.4",
    "vue-router": "^3.0.1",
    "vue-rx": "^6.2.0",
    "vuejs-clipper": "^3.1.1",
    "vuetify": "^2.3.19"
  },
```


If I import like this:

```
import VuejsClipper from 'vuejs-clipper/dist/vuejs-clipper.umd'
import 'vuejs-clipper/dist/vuejs-clipper.css'
import { clipperBasic, clipperPreview, clipperUpload } from 'vuejs-clipper/dist/vuejs-clipper.umd'

```

It successfully builds, and I'm able to use the 'clipper-basic' component :)

However, If I try to import module (without umd file), like this:

`import VuejsClipper from 'vuejs-clipper'
`
It causes errors that I posted before. So it's not really a critical bug, maybe happens with Vue 2 or Vuetify.

**Comment by timtnleeProject** [comment]
Hi @developeralp ,
to import the component like `import VuejsClipper from 'vuejs-clipper'`,
you are using the es-module, which means using the source code directly via your build tool (like Webpack) instead of build files.

You might refer to [use vuejs-clipper soruce](https://github.com/timtnleeProject/vuejs-clipper#use-vuejs-clipper-soruce).
Also, you can find es-module import example at [example branch](https://github.com/timtnleeProject/vuejs-clipper/tree/examples).

**Comment by developeralp** [comment]
Hi,

Sorry I did not understand. 

```
import Vue from 'vue'
import VueRx from 'vue-rx'
import VuejsClipper from 'vuejs-clipper'
// install vue-rx
Vue.use(VueRx)
// install vuejs-clipper
Vue.use(VuejsClipper)
```

So, How can I import like this? (I already tried steps and looked at examples)

It gives me the same errors that I wrote before
