### ISSUE TITLE
Range slider error & documentation faulth

### ISSUE THREAD

**Issue by Cannonb4ll** [timtnleeProject/vuejs-clipper#9]
1.

I am using the <clipper-range> component:

```
<clipper-range v-model="rotation"></clipper-range>
```

But its spitting out these errors:

```
[Vue warn]: Error in directive stream bind hook: "TypeError: Cannot read property 'apply' of undefined"

found in

---> <ClipperRange> at node_modules/vuejs-clipper/src/components/clipper-range.vue
```

It does not seem to work as well.

-------

2.

In your documentation under 'range slider' I read:

```
import { clipperPreview } from 'vuejs-clipper'
```

This is a typo I recon?

**Comment by timtnleeProject** [comment]
2.
It's a typo, it should be `clipperRange`

1.
Did you register component or using the pugin correctly?

Check this [example](https://codepen.io/timtnlee/pen/vzzqRM).

**Comment by Cannonb4ll** [comment]
Yes I think I have:

```
    import {clipperBasic, clipperPreview, clipperRange} from 'vuejs-clipper'

    export default {
        props: {
            image: {
                type: String,
                required: false
            },
            patchUrl: {
                type: String,
                required: false
            }
        },

        components: {
            clipperBasic,
            clipperPreview,
            clipperRange,
        },
```

I have copied over the component from the example but still receiving that same error.

Can I not include this component inside another component?

**Comment by timtnleeProject** [comment]
Hi @Cannonb4ll ,
not sure what causes this error,
but I made a reproduce [here](https://github.com/timtnleeProject/vuejs-clipper-issue-repo/tree/master/issue9) that works fine.

To import these components without using the vuejs-clipper plugin, you need to install:
dependencies: `vue-rx`, `rxjs`
devDependencies: `node-sass`, `sass-loader`

If you have more information please let me know,
thanks

**Comment by timtnleeProject** [comment]
Fixed documentation
