### ISSUE TITLE
Request Flipping and Mirroring features

### ISSUE THREAD

**Issue by sun-lau** [timtnleeProject/vuejs-clipper#90]
When trying input setWH$(-1), unexpected result will come out.
The dragging will operate in wrong way, and actually the canvas image is not flipped/ mirrored 

The sequence of flipping / mirroring step matters, it cannot be done after the positioning and scaling. Thus, it cannot be implemented on canvas after using vuejs-clipper.

**Comment by timtnleeProject** [comment]
Hi @sun-lau , `setWH$(-1)`  -1 is a invalid value, it should > 0.
