### ISSUE TITLE
Toggling corners using mobile devices on clipper-basic bug

### ISSUE THREAD

**Issue by JiafengLiao** [timtnleeProject/vuejs-clipper#91]
**Describe the bug**
The clipper-basic shows different actions when toggling corners. 
The bottem-right corner works fine, adjusted frame size according to the corner point.
Dragging the top-left corner will recreate a frame box.
Dragging the top-right corner will recreate a frame box with same width.
Dragging the bottem-left corner will recreate a frame box with same height.

**To Reproduce**
1. Using clipper-basic on mobile devices.
2. Touch and drag corners on the clipper interface.

**Expected behavior**
The frame resized based on dragging positions.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timtnleeProject** [comment]
Hi @JiafengLiao ,
sorry for the late response,
thanks for your report, I'll get to fix this as soon as I'm available.
Thanks!

**Comment by timtnleeProject** [comment]
Fix at `v3.1.2`

**Comment by JiafengLiao** [comment]
> Hi @JiafengLiao ,
> sorry for the late response,
> thanks for your report, I'll get to fix this as soon as I'm available.
> Thanks!

Thank you for the prompt fix!! I will try that out!

**Comment by JiafengLiao** [comment]
I just tested it and it worked perfectly! Thank you!
