### ISSUE TITLE
Rotation cause image not fully shown in the frame

### ISSUE THREAD

**Issue by JiafengLiao** [timtnleeProject/vuejs-clipper#92]
**Describe the bug**
90 degree rotation cause image not fully shown within the frame. 

**To Reproduce**
Using clipper-basic.
If the hight and width of image are not the same(800x600 for example), the width and height ratio of the frame will be fixed at 4:3.
When use rotate function, the ratio will not change based on the swaped hight and width ratio.  

**Expected behavior**
The frame ratio change to a new value after rotation.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timtnleeProject** [comment]
@JiafengLiao , this is normal behavior.
`clipper-basic` is not designed for rotation and resizing.
## suggestion:
* use `clipper-fix`
* Add control input to rotate, scale image like [this page](https://timtnleeproject.github.io/vuejs-clipper/#/basic).

**Comment by JiafengLiao** [comment]
> @JiafengLiao , this is normal behavior.
> `clipper-basic` is not designed for rotation and resizing.
> 
> ## suggestion:
> * use `clipper-fix`
> * Add control input to rotate, scale image like [this page](https://timtnleeproject.github.io/vuejs-clipper/#/basic).

Thank you! I implement the rotate and rescale functions on the clipper-basic and it works. Yet it is not that user-friendly. 
A small advice is that the frame ratio change based on the image ration change everytime doing the rotation. I will keep looking at the code and see if i can contribute to it. Cheers mate! Great work
