### ISSUE TITLE
Problems with defined ratio

### ISSUE THREAD

**Issue by s1davide** [timtnleeProject/vuejs-clipper#93]
**Describe the bug**
When I set a defined ratio, be it 1 or whatever, at the moment the clipper-basic is loaded, the selection box appears strangely.

![imagen](https://user-images.githubusercontent.com/60453099/105611391-002d4d80-5d83-11eb-88da-34f65bb387cf.png)

**To Reproduce**
Set fixed ratio:
![imagen](https://user-images.githubusercontent.com/60453099/105611455-7df15900-5d83-11eb-9fd5-0861e2e7da89.png)
Then the following happens:
![imagen](https://user-images.githubusercontent.com/60453099/105611391-002d4d80-5d83-11eb-88da-34f65bb387cf.png)

**Expected behavior**
The selection box is expected to be displayed correctly and at the initial size defined in the props.

 - OS: [Windows 10] 
 - Browser [chrome, Firefox]

**Comment by timtnleeProject** [comment]
Hi @s1davide , I cannot reproduce this bug,
if it's possible, could you give more details or use online editor like codepen/codesandbox to reproduce this bug?

**Comment by s1davide** [comment]
Ok, give me some time these days I'm a bit busy, but maybe the problem is because of some conflict with the quasar framework, since, this is based on vue and allows you to use components with defined styles without using style frameworks like bootstrap, I needed to put an image cutter in a "Dialog" and when showing the dialog the square looks like in the image, but this only happened when I set the prop ": ratio=1", because I needed to be able to select only in square, without that prop the selection square appeared correctly but with a varied ratio and adapted to the shape of the selected image.
