### ISSUE TITLE
Can't contain clipper inside dialog

### ISSUE THREAD

**Issue by rferreira98** [timtnleeProject/vuejs-clipper#99]
I have a dialog with the clipper-basic inside. When I put a high res vertical image it becomes a scrollable dialog instead of containing the clipper inside the desired space.
Added max-height and did not work as expected.

**Expected behavior**
I expect it to contain the clipper and the clipper to resize correctly as well to fit the area.

**Screenshots**
![image](https://user-images.githubusercontent.com/24259712/117287061-d693c000-ae61-11eb-8151-28d2e17c16af.png)

**Desktop/Mobile:**
 - OS: Windows 10/ iOS 14
 - Browser: Chrome/Safari

**Comment by timtnleeProject** [comment]
Refer to the doc:
> Components are responsive base on width instead of height, see Component Layout.

@rferreira98 try to style clipper with `width` instead of `height`?

**Comment by rferreira98** [comment]
> Refer to the doc:
> 
> > Components are responsive base on width instead of height, see Component Layout.
> 
> @rferreira98 try to style clipper with `width` instead of `height`?

If the image is bigger than the actual viewport changing the width is not going to fix this issue. The image keeps stretching off viewport regarding its height.

**Comment by timtnleeProject** [comment]
You can set the `wrap-ratio` to fix the size of the clipper.

**Comment by rferreira98** [comment]
> You can set the `wrap-ratio` to fix the size of the clipper.

Wonderful. Did not find my way through the docs to find this by myself. 

Thank you. Amazing package! Keep up!
